/**
 * VECTOR Cultural Fit Lens
 * SCHOOL_CULTURE_CATEGORY — CULTURAL-FIT-LENS-001 (approved spec)
 *
 * Built from school_scorecard_simplified.js (real federal admission rate +
 * in/out tuition data). Category placement only — narrative is generated
 * separately per school so it never reads as generic boilerplate.
 *
 * Categories are derived, never shown as numbers to families.
 * Counselor view may show the underlying admit rate / tuition gap directly.
 */

const SCHOOL_CULTURE_CATEGORY = {
  "Vanderbilt University": "Private / Flat Tuition",
  "University of Michigan": "Exclusive & Protective",
  "Indiana University": "Open Door, Local Lifestyle",
  "University of Georgia": "Exclusive & Protective",
  "University of Florida": "Exclusive & Protective",
  "University of Oklahoma": "Open Door, Local Lifestyle",
  "Louisiana State University": "Broadly Accessible",
  "Auburn University": "Open Door, Local Lifestyle",
  "University of South Carolina": "Open Door, Local Lifestyle",
  "Clemson University": "Exclusive & Protective",
  "Wake Forest University": "Private / Flat Tuition",
  "University of Miami": "Private / Flat Tuition",
  "University of Arizona": "Open Door, Local Lifestyle",
  "Arizona State University": "Open Door, Local Lifestyle",
  "University of Virginia": "Exclusive & Protective",
  "Babson College": "Private / Flat Tuition",
  "Boston University": "Private / Flat Tuition",
  "Dartmouth College": "Private / Flat Tuition",
  "University of Utah": "Open Door, Local Lifestyle",
  "Georgetown University": "Private / Flat Tuition",
  "Duke University": "Private / Flat Tuition",
  "University of Oregon": "Open Door, Local Lifestyle",
  "Stanford University": "Private / Flat Tuition",
  "Williams College": "Private / Flat Tuition",
  "Amherst College": "Private / Flat Tuition",
  "Bowdoin College": "Private / Flat Tuition",
  "Middlebury College": "Private / Flat Tuition",
  "Pomona College": "Private / Flat Tuition",
  "University of Chicago": "Private / Flat Tuition",
  "Penn State University": "Broadly Accessible",
  "Stevens Institute of Technology": "Private / Flat Tuition",
  "UC San Diego": "Exclusive & Protective",
  "Massachusetts Institute of Technology": "Private / Flat Tuition",
  "Georgia Institute of Technology": "Exclusive & Protective",
  "Rose-Hulman Institute of Technology": "Private / Flat Tuition",
  "California Institute of Technology": "Private / Flat Tuition",
  "Carnegie Mellon University": "Private / Flat Tuition",
  "Colorado School of Mines": "Broadly Accessible",
  "Harvey Mudd College": "Private / Flat Tuition",
  "Worcester Polytechnic Institute": "Private / Flat Tuition",
  "University of Washington": "Exclusive & Protective",
  "University of Pennsylvania": "Private / Flat Tuition",
  "Princeton University": "Private / Flat Tuition",
  "Brown University": "Private / Flat Tuition",
  "Harvard University": "Private / Flat Tuition",
  "Yale University": "Private / Flat Tuition",
  "Cornell University": "Private / Flat Tuition",
  "Columbia University": "Private / Flat Tuition",
  "Gonzaga University": "Private / Flat Tuition",
  "Northwestern University": "Private / Flat Tuition",
  "University of Denver": "Private / Flat Tuition",
  "Elon University": "Private / Flat Tuition",
  "Fordham University": "Private / Flat Tuition",
  "University of Kansas": "Open Door, Local Lifestyle",
  "University of Missouri": "Broadly Accessible",
  "University of Arkansas": "Open Door, Local Lifestyle",
  "University of Tennessee": "Broadly Accessible",
  "University of Colorado Boulder": "Open Door, Local Lifestyle",
  "Colorado State University": "Open Door, Local Lifestyle",
  "University of California Davis": "Open Door, Local Lifestyle",
  "Santa Clara University": "Private / Flat Tuition",
  "Saint Mary's College of California": "Private / Flat Tuition",
  "University of Nebraska-Lincoln": "Open Door, Local Lifestyle",
  "Michigan State University": "Open Door, Local Lifestyle",
  "Creighton University": "Private / Flat Tuition",
  "University of Iowa": "Open Door, Local Lifestyle",
  "Drake University": "Private / Flat Tuition",
  "Iowa State University": "Open Door, Local Lifestyle",
  "Ohio State University": "Open Door, Local Lifestyle",
  "University of Notre Dame": "Private / Flat Tuition",
  "Villanova University": "Private / Flat Tuition",
  "Temple University": "Broadly Accessible",
  "Drexel University": "Private / Flat Tuition",
  "UC Riverside": "Open Door, Local Lifestyle",
  "California State University Long Beach": "Open Door, Local Lifestyle",
  "California State University Fullerton": "Open Door, Local Lifestyle",
  "University of California Irvine": "Exclusive & Protective",
  "California Polytechnic State University San Luis Obispo": "Exclusive & Protective",
  "California State University Chico": "Broadly Accessible",
  "California State University Fresno": "Open Door, Local Lifestyle",
  "University of California Santa Cruz": "Open Door, Local Lifestyle",
  "California State University Northridge": "Open Door, Local Lifestyle",
  "California State University Los Angeles": "Open Door, Local Lifestyle",
  "Claremont McKenna College": "Private / Flat Tuition",
  "Pepperdine University": "Private / Flat Tuition",
  "University of San Diego": "Private / Flat Tuition",
  "Oregon State University": "Open Door, Local Lifestyle",
  "Boise State University": "Open Door, Local Lifestyle",
  "Brigham Young University": "Private / Flat Tuition",
  "University of Kentucky": "Open Door, Local Lifestyle",
  "University of Louisville": "Broadly Accessible",
  "University of Minnesota": "Broadly Accessible",
  "Butler University": "Private / Flat Tuition",
  "University of the South": "Private / Flat Tuition",
  "University of Mississippi": "Open Door, Local Lifestyle",
  "Mississippi State University": "Open Door, Local Lifestyle",
  "University of Alabama": "Open Door, Local Lifestyle",
  "Florida State University": "Exclusive & Protective",
  "University of South Florida": "Open Door, Local Lifestyle",
  "University of Central Florida": "Open Door, Local Lifestyle",
  "Florida Atlantic University": "Open Door, Local Lifestyle",
  "Stetson University": "Private / Flat Tuition",
  "Virginia Tech": "Broadly Accessible",
  "Boston College": "Private / Flat Tuition",
  "University of Pittsburgh": "Broadly Accessible",
  "North Carolina State University": "Open Door, Local Lifestyle",
  "University of Maryland College Park": "Open Door, Local Lifestyle",
  "Johns Hopkins University": "Private / Flat Tuition",
  "Emory University": "Private / Flat Tuition",
  "Tulane University": "Private / Flat Tuition",
  "Purdue University": "Open Door, Local Lifestyle",
  "Syracuse University": "Private / Flat Tuition",
  "New York University": "Private / Flat Tuition",
  "Rutgers University": "Broadly Accessible",
  "University of Delaware": "Broadly Accessible",
  "George Washington University": "Private / Flat Tuition",
  "Webb Institute": "Private / Flat Tuition",
  "Colorado College": "Private / Flat Tuition",
  "Kettering University": "Private / Flat Tuition",
  "American University": "Private / Flat Tuition",
  "University of Connecticut": "Broadly Accessible",
  "University of Massachusetts Amherst": "Broadly Accessible",
  "Northeastern University": "Private / Flat Tuition",
  "Case Western Reserve University": "Private / Flat Tuition",
  "University of San Francisco": "Private / Flat Tuition",
  "Baylor University": "Private / Flat Tuition",
  "College of William and Mary": "Selective on Merit",
  "San Diego State University": "Selective on Merit",
  "UC Santa Barbara": "Exclusive & Protective",
  "University of Southern California": "Private / Flat Tuition",
  "UC Berkeley": "Exclusive & Protective",
  "University of California Los Angeles": "Exclusive & Protective",
  "Rice University": "Private / Flat Tuition",
  "Southern Methodist University": "Private / Flat Tuition",
  "Texas Christian University": "Private / Flat Tuition",
  "Texas A&M University": "Open Door, Local Lifestyle",
  "Texas Tech University": "Broadly Accessible",
  "University of Texas at Austin": "Exclusive & Protective",
  "University of North Carolina Chapel Hill": "Exclusive & Protective",
  "Belmont University": "Private / Flat Tuition",
  "Furman University": "Private / Flat Tuition",
  "Wofford College": "Private / Flat Tuition",
  "Rollins College": "Private / Flat Tuition",
  "High Point University": "Private / Flat Tuition",
  "Appalachian State University": "Open Door, Local Lifestyle",
  "University of Tennessee at Chattanooga": "Broadly Accessible",
  "University of Richmond": "Private / Flat Tuition",
  "Washington and Lee University": "Private / Flat Tuition",
  "Howard University": "Private / Flat Tuition",
  "Spelman College": "Private / Flat Tuition",
  "Georgia State University": "Open Door, Local Lifestyle",
  "Flagler College": "Private / Flat Tuition",
  "James Madison University": "Broadly Accessible",
  "University of Memphis": "Broadly Accessible",
  "Regent University": "Private / Flat Tuition",
  "Davidson College": "Private / Flat Tuition",
  "University of Illinois Urbana-Champaign": "Broadly Accessible",
  "University of Wisconsin-Madison": "Open Door, Local Lifestyle",
  "Marquette University": "Private / Flat Tuition",
  "Carleton College": "Private / Flat Tuition",
  "Kenyon College": "Private / Flat Tuition",
  "Oberlin College": "Private / Flat Tuition",
  "Ohio Wesleyan University": "Private / Flat Tuition",
  "Denison University": "Private / Flat Tuition",
  "College of Wooster": "Private / Flat Tuition",
  "Marshall University": "Broadly Accessible",
  "Morehead State University": "Broadly Accessible",
  "North Dakota State University": "Broadly Accessible",
  "South Dakota State University": "Broadly Accessible",
  "Grinnell College": "Private / Flat Tuition",
  "Macalester College": "Private / Flat Tuition",
  "Binghamton University": "Exclusive & Protective",
  "Lehigh University": "Private / Flat Tuition",
  "Quinnipiac University": "Private / Flat Tuition",
  "University of Rhode Island": "Broadly Accessible",
  "Ithaca College": "Private / Flat Tuition",
  "Reed College": "Private / Flat Tuition",
  "Union College": "Private / Flat Tuition",
  "Franklin and Marshall College": "Private / Flat Tuition",
  "Bryn Mawr College": "Private / Flat Tuition",
  "Occidental College": "Private / Flat Tuition",
  "Bentley University": "Private / Flat Tuition",
  "Rhode Island School of Design": "Private / Flat Tuition",
  "Berklee College of Music": "Private / Flat Tuition",
  "Pratt Institute": "Private / Flat Tuition",
  "Rochester Institute of Technology": "Private / Flat Tuition",
  "Fashion Institute of Technology": "Open Door, Local Lifestyle",
  "San Jose State University": "Broadly Accessible",
  "University of Tulsa": "Private / Flat Tuition",
  "University of Idaho": "Open Door, Local Lifestyle",
  "University of Nevada Las Vegas": "Open Door, Local Lifestyle",
  "University of Nevada Reno": "Open Door, Local Lifestyle",
  "University of Montana": "Open Door, Local Lifestyle",
  "Montana State University": "Open Door, Local Lifestyle",
  "University of New Mexico": "Open Door, Local Lifestyle",
  "New Mexico State University": "Open Door, Local Lifestyle",
  "California Lutheran University": "Private / Flat Tuition",
  "California State University San Bernardino": "Open Door, Local Lifestyle",
  "Hamilton College": "Private / Flat Tuition",
  "Swarthmore College": "Private / Flat Tuition",
  "Haverford College": "Private / Flat Tuition",
  "Vassar College": "Private / Flat Tuition",
  "Colgate University": "Private / Flat Tuition",
  "Colby College": "Private / Flat Tuition",
  "Bates College": "Private / Flat Tuition",
  "Bucknell University": "Private / Flat Tuition",
};

const CULTURE_CATEGORY_NARRATIVE = {
  "Exclusive & Protective": "This is a hard room to enter, and it stays close to its own state's identity \u2014 most of the peer group grew up nearby, and coming from out of state means paying a real premium to be part of it.",
  "Open Door, Local Lifestyle": "This room is genuinely easy to enter, but outsiders pay for the privilege \u2014 a strong, distinct regional culture that out-of-state families buy their way into.",
  "Selective on Merit": "This is a hard room to enter, but it's a level playing field \u2014 no hometown advantage, no geographic premium. Merit is what gets you in, regardless of where home is.",
  "Broadly Accessible": "This room is open and evenly priced no matter where a family calls home \u2014 accessible by design, not by exception.",
  "Private / Flat Tuition": "Cost and access here don't shift with geography \u2014 this room's culture reads through its lifestyle and community character rather than a home-state advantage."
};

function getCultureNarrative(schoolName) {
  const cat = SCHOOL_CULTURE_CATEGORY[schoolName];
  if (!cat) return null; // no signal for this school -- omit silently, per spec
  return CULTURE_CATEGORY_NARRATIVE[cat];
}

if (typeof window !== "undefined") { window.SCHOOL_CULTURE_CATEGORY = SCHOOL_CULTURE_CATEGORY; window.getCultureNarrative = getCultureNarrative; }
if (typeof module !== "undefined" && module.exports) { module.exports = { SCHOOL_CULTURE_CATEGORY, CULTURE_CATEGORY_NARRATIVE, getCultureNarrative }; }