/**
 * SCHOOL_CULTURE_CATEGORY
 * Backs the Cultural Fit Lens (CULTURAL-FIT-LENS-001). Parent-facing narrative
 * only -- category placement, never the raw numbers, surfaces to families.
 * Counselors get tuitionRatio/admitRate via this same table for advising.
 *
 * Categories:
 *   Exclusive & Protective       - hard to enter, high OOS tuition premium
 *   Open Door, Local Lifestyle   - easy to enter, high OOS tuition premium
 *   Selective on Merit           - hard to enter, no geographic premium
 *   Broadly Accessible           - easy to enter, no geographic premium
 *   Private / Flat Tuition       - no public in/out signal; culture reads
 *                                  through wealth-tier/lifestyle fields instead
 *
 * Thresholds: admit rate < 0.60 = "hard to enter"; tuition ratio >= 2.2 =
 * "high premium". Derived from the actual distribution across our public-school
 * set (median ratio 2.72x, median admit rate 74%) to avoid an empty category.
 *
 * Source: PUBLIC_DATA.csv (College Scorecard), joined via VECTOR_NAME_CROSSWALK
 * for the ~60 schools whose federal IPEDS name differs from ours.
 */

const SCHOOL_CULTURE_CATEGORY = {
  "American University": { "category": "Private / Flat Tuition" },
  "Amherst College": { "category": "Private / Flat Tuition" },
  "Appalachian State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.33, "admitRate": 0.901 },
  "Arizona State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.71, "admitRate": 0.899 },
  "Auburn University": { "category": "Exclusive & Protective", "tuitionRatio": 2.71, "admitRate": 0.459 },
  "Babson College": { "category": "Private / Flat Tuition" },
  "Barnard College": { "category": "Private / Flat Tuition" },
  "Baylor University": { "category": "Private / Flat Tuition" },
  "Belmont University": { "category": "Private / Flat Tuition" },
  "Bentley University": { "category": "Private / Flat Tuition" },
  "Berklee College of Music": { "category": "Private / Flat Tuition" },
  "Binghamton University": { "category": "Exclusive & Protective", "tuitionRatio": 2.88, "admitRate": 0.386 },
  "Boise State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.07, "admitRate": 0.872 },
  "Boston College": { "category": "Private / Flat Tuition" },
  "Boston University": { "category": "Private / Flat Tuition" },
  "Bowdoin College": { "category": "Private / Flat Tuition" },
  "Brigham Young University": { "category": "Private / Flat Tuition" },
  "Brown University": { "category": "Private / Flat Tuition" },
  "Bryn Mawr College": { "category": "Private / Flat Tuition" },
  "Butler University": { "category": "Private / Flat Tuition" },
  "California Institute of Technology": { "category": "Private / Flat Tuition" },
  "California Lutheran University": { "category": "Private / Flat Tuition" },
  "California Polytechnic State University San Luis Obispo": { "category": "Exclusive & Protective", "tuitionRatio": 2.55, "admitRate": 0.313 },
  "California State University Chico": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.49, "admitRate": 0.927 },
  "California State University Fresno": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.71, "admitRate": 0.953 },
  "California State University Fullerton": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.69, "admitRate": 0.905 },
  "California State University Long Beach": { "category": "Exclusive & Protective", "tuitionRatio": 2.71, "admitRate": 0.463 },
  "California State University Los Angeles": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.76, "admitRate": 0.912 },
  "California State University Maritime Academy": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.27, "admitRate": 0.95 },
  "California State University Northridge": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.69, "admitRate": 0.934 },
  "California State University San Bernardino": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.56, "admitRate": 0.937 },
  "Carleton College": { "category": "Private / Flat Tuition" },
  "Carnegie Mellon University": { "category": "Private / Flat Tuition" },
  "Case Western Reserve University": { "category": "Private / Flat Tuition" },
  "Claremont McKenna College": { "category": "Private / Flat Tuition" },
  "Clemson University": { "category": "Exclusive & Protective", "tuitionRatio": 2.63, "admitRate": 0.383 },
  "College of William and Mary": { "category": "Selective on Merit", "tuitionRatio": 1.97, "admitRate": 0.341 },
  "College of Wooster": { "category": "Private / Flat Tuition" },
  "College of the Ozarks": { "category": "Private / Flat Tuition" },
  "Colorado College": { "category": "Private / Flat Tuition" },
  "Colorado School of Mines": { "category": "Broadly Accessible", "tuitionRatio": 2.09, "admitRate": 0.607 },
  "Colorado State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.6, "admitRate": 0.885 },
  "Columbia University": { "category": "Private / Flat Tuition" },
  "Cornell University": { "category": "Private / Flat Tuition" },
  "Creighton University": { "category": "Private / Flat Tuition" },
  "Dartmouth College": { "category": "Private / Flat Tuition" },
  "Denison University": { "category": "Private / Flat Tuition" },
  "Dickinson College": { "category": "Private / Flat Tuition" },
  "Drake University": { "category": "Private / Flat Tuition" },
  "Drexel University": { "category": "Private / Flat Tuition" },
  "Duke University": { "category": "Private / Flat Tuition" },
  "East Carolina University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.21, "admitRate": 0.892 },
  "Eastern Washington University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.02, "admitRate": 0.907 },
  "Elon University": { "category": "Private / Flat Tuition" },
  "Emory University": { "category": "Private / Flat Tuition" },
  "Fashion Institute of Technology": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.68, "admitRate": 0.602 },
  "Flagler College": { "category": "Private / Flat Tuition" },
  "Florida Atlantic University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.55, "admitRate": 0.661 },
  "Florida State University": { "category": "Exclusive & Protective", "tuitionRatio": 3.32, "admitRate": 0.242 },
  "Fordham University": { "category": "Private / Flat Tuition" },
  "Franklin and Marshall College": { "category": "Private / Flat Tuition" },
  "Furman University": { "category": "Private / Flat Tuition" },
  "George Washington University": { "category": "Private / Flat Tuition" },
  "Georgetown University": { "category": "Private / Flat Tuition" },
  "Georgia Institute of Technology": { "category": "Exclusive & Protective", "tuitionRatio": 2.86, "admitRate": 0.141 },
  "Georgia State University": { "category": "Exclusive & Protective", "tuitionRatio": 2.87, "admitRate": 0.554 },
  "Gettysburg College": { "category": "Private / Flat Tuition" },
  "Gonzaga University": { "category": "Private / Flat Tuition" },
  "Grinnell College": { "category": "Private / Flat Tuition" },
  "Hamilton College": { "category": "Private / Flat Tuition" },
  "Harvard University": { "category": "Private / Flat Tuition" },
  "Harvey Mudd College": { "category": "Private / Flat Tuition" },
  "High Point University": { "category": "Private / Flat Tuition" },
  "Howard University": { "category": "Private / Flat Tuition" },
  "Illinois Wesleyan University": { "category": "Private / Flat Tuition" },
  "Indiana University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.45, "admitRate": 0.782 },
  "Iowa State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.68, "admitRate": 0.887 },
  "Ithaca College": { "category": "Private / Flat Tuition" },
  "James Madison University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.22, "admitRate": 0.715 },
  "Johns Hopkins University": { "category": "Private / Flat Tuition" },
  "Kenyon College": { "category": "Private / Flat Tuition" },
  "Kettering University": { "category": "Private / Flat Tuition" },
  "Lehigh University": { "category": "Private / Flat Tuition" },
  "Louisiana State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.4, "admitRate": 0.733 },
  "Maine Maritime Academy": { "category": "Selective on Merit", "tuitionRatio": 2.05, "admitRate": 0.541 },
  "Marquette University": { "category": "Private / Flat Tuition" },
  "Marshall University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.22, "admitRate": 0.957 },
  "Massachusetts Institute of Technology": { "category": "Private / Flat Tuition" },
  "Massachusetts Maritime Academy": { "category": "Broadly Accessible", "tuitionRatio": 2.08, "admitRate": 0.947 },
  "Michigan State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.66, "admitRate": 0.848 },
  "Middlebury College": { "category": "Private / Flat Tuition" },
  "Mississippi State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.71, "admitRate": 0.776 },
  "Montana State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.93, "admitRate": 0.821 },
  "Morehead State University": { "category": "Broadly Accessible", "tuitionRatio": 1.49, "admitRate": 0.772 },
  "New Mexico State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.09, "admitRate": 0.89 },
  "New York University": { "category": "Private / Flat Tuition" },
  "North Carolina State University": { "category": "Exclusive & Protective", "tuitionRatio": 3.73, "admitRate": 0.417 },
  "North Dakota State University": { "category": "Broadly Accessible", "tuitionRatio": 1.42, "admitRate": 0.95 },
  "Northeastern University": { "category": "Private / Flat Tuition" },
  "Northwestern University": { "category": "Private / Flat Tuition" },
  "Oberlin College": { "category": "Private / Flat Tuition" },
  "Occidental College": { "category": "Private / Flat Tuition" },
  "Ohio State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.02, "admitRate": 0.606 },
  "Ohio Wesleyan University": { "category": "Private / Flat Tuition" },
  "Oregon State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.65, "admitRate": 0.773 },
  "Penn State University": { "category": "Broadly Accessible", "tuitionRatio": 2.02, "admitRate": 0.606 },
  "Pepperdine University": { "category": "Private / Flat Tuition" },
  "Pomona College": { "category": "Private / Flat Tuition" },
  "Pratt Institute": { "category": "Private / Flat Tuition" },
  "Princeton University": { "category": "Private / Flat Tuition" },
  "Providence College": { "category": "Private / Flat Tuition" },
  "Purdue University": { "category": "Exclusive & Protective", "tuitionRatio": 2.88, "admitRate": 0.499 },
  "Quinnipiac University": { "category": "Private / Flat Tuition" },
  "Reed College": { "category": "Private / Flat Tuition" },
  "Regent University": { "category": "Private / Flat Tuition" },
  "Rhode Island School of Design": { "category": "Private / Flat Tuition" },
  "Rice University": { "category": "Private / Flat Tuition" },
  "Rochester Institute of Technology": { "category": "Private / Flat Tuition" },
  "Rollins College": { "category": "Private / Flat Tuition" },
  "Rose-Hulman Institute of Technology": { "category": "Private / Flat Tuition" },
  "Rutgers University": { "category": "Selective on Merit", "tuitionRatio": 2.09, "admitRate": 0.582 },
  "SMU": { "category": "Private / Flat Tuition" },
  "Saint Mary's College of California": { "category": "Private / Flat Tuition" },
  "Sam Houston State University": { "category": "Broadly Accessible", "tuitionRatio": 2.07, "admitRate": 0.903 },
  "San Diego State University": { "category": "Exclusive & Protective", "tuitionRatio": 2.44, "admitRate": 0.362 },
  "San Francisco State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.58, "admitRate": 0.964 },
  "San Jose State University": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.5, "admitRate": 0.846 },
  "Santa Clara University": { "category": "Private / Flat Tuition" },
  "South Dakota State University": { "category": "Broadly Accessible", "tuitionRatio": 1.38, "admitRate": 0.983 },
  "Spelman College": { "category": "Private / Flat Tuition" },
  "St. John's College": { "category": "Private / Flat Tuition" },
  "Stanford University": { "category": "Private / Flat Tuition" },
  "Stetson University": { "category": "Private / Flat Tuition" },
  "Stevens Institute of Technology": { "category": "Private / Flat Tuition" },
  "Syracuse University": { "category": "Private / Flat Tuition" },
  "TCU": { "category": "Private / Flat Tuition" },
  "Temple University": { "category": "Broadly Accessible", "tuitionRatio": 1.69, "admitRate": 0.804 },
  "Texas A&M University": { "category": "Exclusive & Protective", "tuitionRatio": 3.05, "admitRate": 0.574 },
  "Texas State University": { "category": "Broadly Accessible", "tuitionRatio": 2.0, "admitRate": 0.893 },
  "Texas Tech University": { "category": "Broadly Accessible", "tuitionRatio": 2.06, "admitRate": 0.727 },
  "Tulane University": { "category": "Private / Flat Tuition" },
  "UC Berkeley": { "category": "Exclusive & Protective", "tuitionRatio": 3.09, "admitRate": 0.11 },
  "UC Riverside": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.19, "admitRate": 0.764 },
  "UC San Diego": { "category": "Exclusive & Protective", "tuitionRatio": 3.04, "admitRate": 0.267 },
  "UC Santa Barbara": { "category": "Exclusive & Protective", "tuitionRatio": 3.08, "admitRate": 0.33 },
  "UCLA": { "category": "Exclusive & Protective", "tuitionRatio": 3.25, "admitRate": 0.09 },
  "USC": { "category": "Private / Flat Tuition" },
  "UT Austin": { "category": "Exclusive & Protective", "tuitionRatio": 3.84, "admitRate": 0.266 },
  "Union College": { "category": "Private / Flat Tuition" },
  "United States Merchant Marine Academy": { "category": "Selective on Merit", "tuitionRatio": 1.0, "admitRate": 0.342 },
  "University of Alabama": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.81, "admitRate": 0.766 },
  "University of Arizona": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.04, "admitRate": 0.861 },
  "University of Arkansas": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.97, "admitRate": 0.743 },
  "University of California Davis": { "category": "Exclusive & Protective", "tuitionRatio": 3.04, "admitRate": 0.418 },
  "University of California Irvine": { "category": "Exclusive & Protective", "tuitionRatio": 3.18, "admitRate": 0.286 },
  "University of California Santa Cruz": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.14, "admitRate": 0.658 },
  "University of Central Florida": { "category": "Exclusive & Protective", "tuitionRatio": 3.53, "admitRate": 0.401 },
  "University of Chicago": { "category": "Private / Flat Tuition" },
  "University of Colorado Boulder": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.87, "admitRate": 0.781 },
  "University of Connecticut": { "category": "Selective on Merit", "tuitionRatio": 2.08, "admitRate": 0.524 },
  "University of Denver": { "category": "Private / Flat Tuition" },
  "University of Florida": { "category": "Exclusive & Protective", "tuitionRatio": 4.49, "admitRate": 0.242 },
  "University of Georgia": { "category": "Exclusive & Protective", "tuitionRatio": 2.77, "admitRate": 0.377 },
  "University of Hawaii at Manoa": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.81, "admitRate": 0.866 },
  "University of Idaho": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.12, "admitRate": 0.755 },
  "University of Illinois Urbana-Champaign": { "category": "Selective on Merit", "tuitionRatio": 2.19, "admitRate": 0.424 },
  "University of Iowa": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.96, "admitRate": 0.836 },
  "University of Kansas": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.51, "admitRate": 0.935 },
  "University of Kentucky": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.53, "admitRate": 0.929 },
  "University of Louisville": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.24, "admitRate": 0.794 },
  "University of Maryland College Park": { "category": "Exclusive & Protective", "tuitionRatio": 3.49, "admitRate": 0.448 },
  "University of Memphis": { "category": "Broadly Accessible", "tuitionRatio": 1.43, "admitRate": 0.72 },
  "University of Miami": { "category": "Private / Flat Tuition" },
  "University of Michigan": { "category": "Exclusive & Protective", "tuitionRatio": 3.44, "admitRate": 0.156 },
  "University of Minnesota": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.23, "admitRate": 0.797 },
  "University of Mississippi": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.93, "admitRate": 0.966 },
  "University of Missouri": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.43, "admitRate": 0.785 },
  "University of Montana": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.94, "admitRate": 0.959 },
  "University of Nebraska-Lincoln": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.74, "admitRate": 0.875 },
  "University of Nevada Las Vegas": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.81, "admitRate": 0.962 },
  "University of Nevada Reno": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.89, "admitRate": 0.737 },
  "University of New Mexico": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.26, "admitRate": 0.952 },
  "University of North Carolina Chapel Hill": { "category": "Exclusive & Protective", "tuitionRatio": 4.58, "admitRate": 0.153 },
  "University of North Texas": { "category": "Broadly Accessible", "tuitionRatio": 1.87, "admitRate": 0.722 },
  "University of Notre Dame": { "category": "Private / Flat Tuition" },
  "University of Oklahoma": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.79, "admitRate": 0.766 },
  "University of Oregon": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.76, "admitRate": 0.883 },
  "University of Pennsylvania": { "category": "Private / Flat Tuition" },
  "University of Pittsburgh": { "category": "Selective on Merit", "tuitionRatio": 1.89, "admitRate": 0.581 },
  "University of Rhode Island": { "category": "Broadly Accessible", "tuitionRatio": 2.19, "admitRate": 0.722 },
  "University of Richmond": { "category": "Private / Flat Tuition" },
  "University of San Diego": { "category": "Private / Flat Tuition" },
  "University of San Francisco": { "category": "Private / Flat Tuition" },
  "University of South Carolina": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.84, "admitRate": 0.602 },
  "University of South Florida": { "category": "Exclusive & Protective", "tuitionRatio": 2.7, "admitRate": 0.432 },
  "University of Tennessee": { "category": "Exclusive & Protective", "tuitionRatio": 2.41, "admitRate": 0.416 },
  "University of Tennessee at Chattanooga": { "category": "Broadly Accessible", "tuitionRatio": 1.77, "admitRate": 0.811 },
  "University of Tulsa": { "category": "Private / Flat Tuition" },
  "University of Utah": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.21, "admitRate": 0.86 },
  "University of Vermont": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 2.39, "admitRate": 0.653 },
  "University of Virginia": { "category": "Exclusive & Protective", "tuitionRatio": 2.73, "admitRate": 0.168 },
  "University of Washington": { "category": "Exclusive & Protective", "tuitionRatio": 3.33, "admitRate": 0.392 },
  "University of Wisconsin-Madison": { "category": "Exclusive & Protective", "tuitionRatio": 3.63, "admitRate": 0.452 },
  "University of Wyoming": { "category": "Open Door, Local Lifestyle", "tuitionRatio": 3.11, "admitRate": 0.969 },
  "University of the South": { "category": "Private / Flat Tuition" },
  "Vanderbilt University": { "category": "Private / Flat Tuition" },
  "Vassar College": { "category": "Private / Flat Tuition" },
  "Villanova University": { "category": "Private / Flat Tuition" },
  "Virginia Tech": { "category": "Exclusive & Protective", "tuitionRatio": 2.37, "admitRate": 0.548 },
  "Wake Forest University": { "category": "Private / Flat Tuition" },
  "Washington and Lee University": { "category": "Private / Flat Tuition" },
  "Webb Institute": { "category": "Private / Flat Tuition" },
  "Wesleyan University": { "category": "Private / Flat Tuition" },
  "Williams College": { "category": "Private / Flat Tuition" },
  "Wofford College": { "category": "Private / Flat Tuition" },
  "Worcester Polytechnic Institute": { "category": "Private / Flat Tuition" },
  "Yale University": { "category": "Private / Flat Tuition" },
};

if (typeof module !== "undefined") module.exports = { SCHOOL_CULTURE_CATEGORY };