/**
 * VECTOR_NAME_CROSSWALK
 * Maps VECTOR's canonical school name -> official College Scorecard INSTNM.
 * Only contains the ~60 schools whose Scorecard name differs from ours;
 * schools with an exact-match name need no entry (161 of 221 already match directly).
 * null = confirmed not present in the federal Scorecard dataset under any name.
 */

const VECTOR_NAME_CROSSWALK = {
  "Arizona State University": "Arizona State University Campus Immersion",
  "California Polytechnic State University San Luis Obispo": "California Polytechnic State University-San Luis Obispo",
  "California State University Chico": "California State University-Chico",
  "California State University Fresno": "California State University-Fresno",
  "California State University Fullerton": "California State University-Fullerton",
  "California State University Long Beach": "California State University-Long Beach",
  "California State University Los Angeles": "California State University-Los Angeles",
  "California State University Maritime Academy": "Cal Poly Maritime Academy",
  "California State University Northridge": "California State University-Northridge",
  "California State University San Bernardino": "California State University-San Bernardino",
  "College of William and Mary": "William & Mary",
  "College of Wooster": "The College of Wooster",
  "Colorado State University": "Colorado State University-Fort Collins",
  "Columbia University": "Columbia University in the City of New York",
  "Deep Springs College": null,
  "Georgia Institute of Technology": "Georgia Institute of Technology-Main Campus",
  "Indiana University": "Indiana University-Bloomington",
  "Louisiana State University": "Louisiana State University and Agricultural & Mechanical College",
  "New Mexico State University": "New Mexico State University-Main Campus",
  "North Carolina State University": "North Carolina State University at Raleigh",
  "North Dakota State University": "North Dakota State University-Main Campus",
  "Ohio State University": "Ohio State University-Main Campus",
  "Penn State University": "Pennsylvania State University-Main Campus",
  "Pratt Institute": "Pratt Institute-Main",
  "Purdue University": "Purdue University-Main Campus",
  "Rutgers University": "Rutgers University-New Brunswick",
  "SMU": "Southern Methodist University",
  "TCU": "Texas Christian University",
  "Texas A&M University": "Texas A&M University-College Station",
  "Texas A&M University at Galveston": null,
  "Tulane University": "Tulane University of Louisiana",
  "UC Berkeley": "University of California-Berkeley",
  "UC Riverside": "University of California-Riverside",
  "UC San Diego": "University of California-San Diego",
  "UC Santa Barbara": "University of California-Santa Barbara",
  "UCLA": "University of California-Los Angeles",
  "USC": "University of Southern California",
  "UT Austin": "The University of Texas at Austin",
  "University of Alabama": "The University of Alabama",
  "University of California Davis": "University of California-Davis",
  "University of California Irvine": "University of California-Irvine",
  "University of California Santa Cruz": "University of California-Santa Cruz",
  "University of Maryland College Park": "University of Maryland-College Park",
  "University of Michigan": "University of Michigan-Ann Arbor",
  "University of Minnesota": "University of Minnesota-Twin Cities",
  "University of Missouri": "University of Missouri-Columbia",
  "University of Montana": "The University of Montana",
  "University of Nevada Las Vegas": "University of Nevada-Las Vegas",
  "University of Nevada Reno": "University of Nevada-Reno",
  "University of New Mexico": "University of New Mexico-Main Campus",
  "University of North Carolina Chapel Hill": "University of North Carolina at Chapel Hill",
  "University of Oklahoma": "University of Oklahoma-Norman Campus",
  "University of Pittsburgh": "University of Pittsburgh-Pittsburgh Campus",
  "University of South Carolina": "University of South Carolina-Columbia",
  "University of Tennessee": "The University of Tennessee-Knoxville",
  "University of Tennessee at Chattanooga": "The University of Tennessee-Chattanooga",
  "University of Virginia": "University of Virginia-Main Campus",
  "University of Washington": "University of Washington-Seattle Campus",
  "University of the South": "The University of the South",
  "Virginia Tech": "Virginia Polytechnic Institute and State University",
};

if (typeof module !== "undefined") module.exports = { VECTOR_NAME_CROSSWALK };